# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McapEncrypt < Formula
  desc "Chunk-level encryption for MCAP robotics data files"
  homepage "https://github.com/remete618/mcap-encrypt"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.4.0/mcap-encrypt_0.4.0_darwin_amd64.tar.gz"
      sha256 "bee1e550ab8da9e6005bf5c0e88f0777233e62619c25e6dbed85ce425a681fe0"

      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.4.0/mcap-encrypt_0.4.0_darwin_arm64.tar.gz"
      sha256 "7f833ec02dc302d2e60a3854c4845db85698e88b449439ab7dfdc0793c3f0600"

      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.4.0/mcap-encrypt_0.4.0_linux_amd64.tar.gz"
      sha256 "12bf772cfa838dd35f34a5cf85f23169f7346f61224e12a766fec123da5e3673"
      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.4.0/mcap-encrypt_0.4.0_linux_arm64.tar.gz"
      sha256 "43413cbc01e2b4dd120f1246bcbb32aa63912633162c1686e29d71d2c7b9834f"
      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
  end

  test do
    assert_match "mcap-encrypt #{version}", shell_output("#{bin}/mcap-encrypt version")
    system bin/"mcap-encrypt", "keygen", "--out", "tk"
    assert_path_exists testpath/"tk.pub.pem"
    assert_path_exists testpath/"tk.priv.pem"
  end
end
