# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McapEncrypt < Formula
  desc "Chunk-level encryption for MCAP robotics data files"
  homepage "https://github.com/remete618/mcap-encrypt"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.9.0/mcap-encrypt_0.9.0_darwin_amd64.tar.gz"
      sha256 "31565a3f7a442e9172002951ebad7a6c0251e2d397f76ce765d3b701673a1182"

      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.9.0/mcap-encrypt_0.9.0_darwin_arm64.tar.gz"
      sha256 "a13b4b20f58ac80806871338a30ae4675817276e0c64cfce226548523c3302cd"

      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.9.0/mcap-encrypt_0.9.0_linux_amd64.tar.gz"
      sha256 "6ca8a2ccac0b020d369f3d0dfd1922845705e55ce6709722ba824734d6af09b3"
      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/remete618/mcap-encrypt/releases/download/v0.9.0/mcap-encrypt_0.9.0_linux_arm64.tar.gz"
      sha256 "75d9709a6288ce6990da4c27fec9beaa68d6173eecbd5a1a8c8db0ad2c428fed"
      define_method(:install) do
        bin.install "mcap-encrypt"
      end
    end
  end

  test do
    assert_match "mcap-encrypt #{version}", shell_output("#{bin}/mcap-encrypt version")
    system bin/"mcap-encrypt", "keygen", "--out", "tk"
    assert_path_exists testpath/"tk.pub.pem"
    assert_path_exists testpath/"tk.priv.pem"
  end
end
